---

- name: Ensure IncludeConfig is in main config file
  ansible.builtin.lineinfile:
    path: "{{ rsyslog_file_conf }}"
    regexp: '^\$IncludeConfig\s+{{ rsyslog_dir_conf }}'
    line: "$IncludeConfig {{ rsyslog_dir_conf }}/*.conf"
  notify:
    - restart rsyslog

- name: "setup rsyslog configuration"
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ rsyslog_dir_conf }}/{{ file.dest }}"
    owner: root
    group: root
    mode: 0640
  loop: "{{ rsyslog_conf_files }}"
  loop_control:
    loop_var: file
  notify:
    - restart rsyslog
