---

- name: Ensure IncludeConfig is in main confog file
  ansible.builtin.lineinfile:
    path: "{{ rsyslog_file_conf }}"
    regexp: '^\$IncludeConfig\s+{{ rsyslog_dir_conf }}/.*.conf'
    line: "$IncludeConfig {{ rsyslog_dir_conf }}"

- name: "setup rsyslog configuration"
  ansible.builtin.template:
    src: "{{ file.src }}"
    dest: "{{ rsyslog_dir_conf }}/{{ file.dest | default(file.src)}}"
    owner: root
    group: root
    mode: 0640
  loop: "{{ rsyslog_conf_files }}"
  loop_control:
    loop_var: file
  notify:
    - restart rsyslog
