---
# tasks file for rsyslog

- name: Add the OS specific varibles
  ansible.builtin.include_vars: "os-{{ ansible_os_family }}.yml"
  tags:
    - always

# Debian(setup) specific tasks
- name: include packages tasks
  ansible.builtin.include_tasks:
    file: packages-{{ ansible_os_family }}.yml
    apply:
      tags:
        - rsyslog
        - rsyslog:setup
  tags:
    - always

# Common configuration tasks tasks
- name: include config tasks
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - rsyslog
        - rsyslog:config
  tags:
    - always

# Common service tasks
- name: include service tasks
  ansible.builtin.include_tasks:
    file: service.yml
    apply:
      tags:
        - rsyslog
        - rsyslog:service
  tags:
    - always